"""empty message

Revision ID: c4a76d52af6c
Revises:
Create Date: 2023-02-25 14:30:49.914466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a76d52af6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spider', sa.String(length=128), nullable=True),
    sa.Column('place', sa.String(length=128), nullable=True),
    sa.Column('zipcode', sa.String(length=32), nullable=True),
    sa.Column('date_slot', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('recipients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_history')
    # ### end Alembic commands ###
